# 返回书名的时候需要的映射(字典)

name_mapping = {
    'BEC_2': 'BEC第2册',
    'BEC_3': 'BEC第3册',
    'BeiShiGaoZhong_1': '北师高中第1册',
    'BeiShiGaoZhong_10': '北师高中第10册',
    'BeiShiGaoZhong_11': '北师高中第11册',
    'BeiShiGaoZhong_2': '北师高中第2册',
    'BeiShiGaoZhong_3': '北师高中第3册',
    'BeiShiGaoZhong_4': '北师高中第4册',
    'BeiShiGaoZhong_5': '北师高中第5册',
    'BeiShiGaoZhong_6': '北师高中第6册',
    'BeiShiGaoZhong_7': '北师高中第7册',
    'BeiShiGaoZhong_8': '北师高中第8册',
    'BeiShiGaoZhong_9': '北师高中第9册',
    'CET4luan_1': 'CET4第1册乱序',
    'CET4luan_2': 'CET4第2册乱序',
    'CET4_1': 'CET4第1册',
    'CET4_2': 'CET4第2册',
    'CET4_3': 'CET4第3册',
    'CET6luan_1': 'CET6第1册乱序',
    'CET6_1': 'CET6第1册',
    'CET6_2': 'CET6第2册',
    'CET6_3': 'CET6第3册',
    'ChuZhongluan_2': '初中第2册乱序',
    'ChuZhong_2': '初中第2册',
    'ChuZhong_3': '初中第3册',
    'GaoZhongluan_2': '高中第2册乱序',
    'GaoZhong_2': '高中第2册',
    'GaoZhong_3': '高中第3册',
    'GMATluan_2': 'GMAT第2册乱序',
    'GMAT_2': 'GMAT第2册',
    'GMAT_3': 'GMAT第3册',
    'GRE_2': 'GRE第2册',
    'GRE_3': 'GRE第3册',
    'IELTSluan_2': 'IELTS第2册乱序',
    'IELTS_2': 'IELTS第2册',
    'IELTS_3': 'IELTS第3册',
    'KaoYanluan_1': '考研第1册乱序',
    'KaoYan_1': '考研第1册',
    'KaoYan_2': '考研第2册',
    'KaoYan_3': '考研第3册',
    'Level4luan_1': 'Level4第1册乱序',
    'Level4luan_2': 'Level4第2册乱序',
    'Level4_1': 'Level4第1册',
    'Level4_2': 'Level4第2册',
    'Level8luan_2': 'Level8第2册乱序',
    'Level8_1': 'Level8第1册',
    'Level8_2': 'Level8第2册',
    'PEPChuZhong7_1': 'PEP初中7第1册',
    'PEPChuZhong7_2': 'PEP初中7第2册',
    'PEPChuZhong8_1': 'PEP初中8第1册',
    'PEPChuZhong8_2': 'PEP初中8第2册',
    'PEPChuZhong9_1': 'PEP初中9第1册',
    'PEPGaoZhong_1': 'PEP高中第1册',
    'PEPGaoZhong_10': 'PEP高中第10册',
    'PEPGaoZhong_11': 'PEP高中第11册',
    'PEPGaoZhong_2': 'PEP高中第2册',
    'PEPGaoZhong_3': 'PEP高中第3册',
    'PEPGaoZhong_4': 'PEP高中第4册',
    'PEPGaoZhong_5': 'PEP高中第5册',
    'PEPGaoZhong_6': 'PEP高中第6册',
    'PEPGaoZhong_7': 'PEP高中第7册',
    'PEPGaoZhong_8': 'PEP高中第8册',
    'PEPGaoZhong_9': 'PEP高中第9册',
    'PEPXiaoXue3_1': 'PEP小学3第1册',
    'PEPXiaoXue3_2': 'PEP小学3第2册',
    'PEPXiaoXue4_1': 'PEP小学4第1册',
    'PEPXiaoXue4_2': 'PEP小学4第2册',
    'PEPXiaoXue5_1': 'PEP小学5第1册',
    'PEPXiaoXue5_2': 'PEP小学5第2册',
    'PEPXiaoXue6_1': 'PEP小学6第1册',
    'PEPXiaoXue6_2': 'PEP小学6第2册',
    'SAT_2': 'SAT第2册',
    'SAT_3': 'SAT第3册',
    'TOEFL_2': 'TOEFL第2册',
    'TOEFL_3': 'TOEFL第3册',
    'WaiYanSheChuZhong_1': '外研社初中第1册',
    'WaiYanSheChuZhong_2': '外研社初中第2册',
    'WaiYanSheChuZhong_3': '外研社初中第3册',
    'WaiYanSheChuZhong_4': '外研社初中第4册',
    'WaiYanSheChuZhong_5': '外研社初中第5册',
    'WaiYanSheChuZhong_6': '外研社初中第6册',
}

# 不同教育等级的人推送不同
# 我们按以下规则分级
#
# 小学 0
# 初中 1
# 高中 2
# 大学及以上 3
#
# 每个等级对应一个 ~~数组~~ 列表 数组中含有对应的所有书

rank_mapping = {
    0: [
        'PEPXiaoXue3_1',
        'PEPXiaoXue3_2',
        'PEPXiaoXue4_1',
        'PEPXiaoXue4_2',
        'PEPXiaoXue5_1',
        'PEPXiaoXue5_2',
        'PEPXiaoXue6_1',
        'PEPXiaoXue6_2',
    ],
    1: [
        'WaiYanSheChuZhong_1',
        'WaiYanSheChuZhong_2',
        'WaiYanSheChuZhong_3',
        'WaiYanSheChuZhong_4',
        'WaiYanSheChuZhong_5',
        'WaiYanSheChuZhong_6',
        'PEPChuZhong7_1',
        'PEPChuZhong7_2',
        'PEPChuZhong8_1',
        'PEPChuZhong8_2',
        'PEPChuZhong9_1',
        'ChuZhongluan_2',
        'ChuZhong_2',
        'ChuZhong_3',
        'GaoZhongluan_2',
        'GaoZhong_2',
        'GaoZhong_3',
    ],
    2: [
        'BeiShiGaoZhong_1',
        'BeiShiGaoZhong_11',
        'BeiShiGaoZhong_2',
        'BeiShiGaoZhong_3',
        'BeiShiGaoZhong_4',
        'BeiShiGaoZhong_5',
        'BeiShiGaoZhong_6',
        'BeiShiGaoZhong_7',
        'BeiShiGaoZhong_8',
        'BeiShiGaoZhong_9',
        'BeiShiGaoZhong_10',
        'PEPGaoZhong_1',
        'PEPGaoZhong_10',
        'PEPGaoZhong_11',
        'PEPGaoZhong_2',
        'PEPGaoZhong_3',
        'PEPGaoZhong_4',
        'PEPGaoZhong_5',
        'PEPGaoZhong_6',
        'PEPGaoZhong_7',
        'PEPGaoZhong_8',
        'PEPGaoZhong_9',
    ],
    3: [
        'CET4luan_1',
        'CET4luan_2',
        'CET4_1',
        'CET4_2',
        'CET4_3',
        'CET6luan_1',
        'CET6_1',
        'CET6_2',
        'CET6_3',
        'BEC_2',
        'BEC_3',
        'GMATluan_2',
        'GMAT_2',
        'GMAT_3',
        'GRE_2',
        'GRE_3',
        'IELTSluan_2',
        'IELTS_2',
        'IELTS_3',
        'KaoYanluan_1',
        'KaoYan_1',
        'KaoYan_2',
        'KaoYan_3',
        'Level4luan_1',
        'Level4luan_2',
        'Level4_1',
        'Level4_2',
        'Level8luan_2',
        'Level8_1',
        'Level8_2',
        'SAT_2',
        'SAT_3',
        'TOEFL_2',
        'TOEFL_3',
    ]
}
